Sportamore/blues

blues/rabbitmq.py
blues/templates/rabbitmq/default/rabbitmq-server

Add recommended ulimit allotment to rabbitmq init settings

Add service config for rabbitmq server, with more file handles

---

blues/application/providers/celery.py
blues/application/providers/program.py
blues/application/providers/uwsgi.py
blues/application/tasks.py
blues/uwsgi.py

Add basic app stats to uwsgi-provided apps, to verify reloads

Infra 191 app status

---

blues/rabbitmq.py

Simple, conventient command for adding users to a rabbitmq server

Add simple useradd commands

---

blues/shell.py
blues/templates/shell/bash_aliases
blues/templates/shell/bash_profile
blues/templates/shell/bashrc

Basic bash templates for /etc/skel and root

Shell profile template

---

blues/application/providers/celery.py
blues/templates/app/supervisor/default/celery.conf

This should have gone into https://github.com/Sportamore/blues/pull/17

Simplified celery provider

---

blues/application/providers/celery.py
blues/templates/app/supervisor/default/celery.conf

...i.e. queues don't have to be defined in the same role.
Please release this as 1.3.17.

[SCS-38] Beat without queues

---

blues/wkhtmltopdf.py

New link for wkhtmltox Old link was broken

New link for wkhtmltox Old link was broken

---

blues/templates/uwsgi/init.d/uwsgi
blues/uwsgi.py

I based my solution on the ssh init script.
/lib/lsb/init-functions has a function called init_is_upstart that i am using

Added a init.d script for uwsgi. See case SWMS-61 for details.

---

blues/templates/postgres/pg_hba.conf

Change so that pg_basebackup works without any modification

Changed template to allow pg_basebackup from the start

---

blues/__init__.py

Bump version

---

blues/dhcp.py
blues/templates/dhcp/dhcpd.conf
blues/templates/dhcp/isc-dhcp-server

Blueprint for dhcp

---

blues/debian.py

Boot flags fstab

---

.gitignore
blues/docker.py
blues/templates/docker/docker-system-prune.sh

We want to clean up docker servers with cronjobs. Added some tasks that manage cronjobs that do this.

Ops-749: Added tasks that manage Docker pruning cronjobs

---

blues/check_mk.py
blues/templates/check_mk/check_mk_agent.linux
blues/templates/check_mk/check_mk_caching_agent.linux
blues/templates/check_mk/check_mk_template

plugins directory for special made checks
check_mk directory for settings on checks and client config files

First version of fixing the check_mk agent to blues.

---

blues/debian.py
blues/java.py
blues/newrelic.py
blues/node.py
blues/python.py
blues/solr.py
blues/supervisor.py
blues/uwsgi.py

Lots of things broke for ubuntu 18.04. This should fix most of them at least :crossed_fingers:

Branch: 18.04_test     Update blues for 18.04 

---

blues/elasticsearch.py
blues/templates/elasticsearch/jvm.options

Rebased our jvm.options config on the latest default
Add support for readonly elastic repositories.

SCS-1726_small_fixes

---

blues/check_mk.py
blues/elasticsearch.py

Indentation fix in check_mk code and updated documentation as well as default elasticsearch version

SCS-1769: staging elastic

---

blues/django.py

Expose nr of unapplied migrations so that we can base decisions on it in fabric.

SCS-1949: Expose nr of unapplied migrations

---

blues/elasticsearch.py

Upload the logfile template to elasticsearch machines

OPS-1157:Upload log4j2 to elasticsearch

---

blues/supervisor.py
blues/templates/supervisor/tmpfiles.d/supervisor.conf
blues/templates/uwsgi/systemd/uwsgi.service
blues/templates/uwsgi/tmpfiles.d/uwsgi.conf
blues/uwsgi.py

tmpfiles.d added other changes moved to deploy repo

18.04 test

---

blues/beats.py
blues/templates/beats/filebeat.yml
blues/templates/beats/metricbeat.yml

Should help with the inconsistent logs

OPS-1246: Fix "type" field name conflict
